server:
  port: 8080
spring:
  application:
    name: MyBlog
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&useOldAliasMetadataBehavior=true&allowMultiQueries=true
    username: root
    password: zhaojunhao
    driver-class-name: com.mysql.cj.jdbc.Driver

